---
- name: Wait 300 seconds for port 3306 to become open on the host, don't start checking for 10 seconds  -  Backup XtraBackup for {{ mysql_version.stdout }}
  wait_for:
    port: 3306
    delay: 10